name: Windows

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gnu:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-netcdf
          mingw-w64-x86_64-netcdf-fortran
        msystem: MINGW64

    - name: Configure with CMake
      run: cmake -G "MinGW Makefiles" -B build -D CMAKE_PREFIX_PATH=C:/msys64/mingw64 -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build the project
      run: cmake --build build
